output   = "database/models"
wipe     = true
no-tests = true

[psql]
  dbname = "test"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "password"
  sslmode = "disable"
  schema = "public"
  blacklist = ["schema_migrations"]